server {
    listen 80;

    location /stocks/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /stocks/index.html;
    }

    location /stocks {
        return 301 /stocks/;
    }

    location /api/ {
        proxy_pass http://stocks-backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
